name: Deploy
on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 安装pnpm
      - name: prepare pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2

      # 下载源码
      - name: Checkout
        uses: actions/checkout@master

      # 打包构建
      - name: Build
        uses: actions/setup-node@master
      - run: pnpm install --shamefully-hoist
      - run: pnpm run build
      - run: tar -zcvf youus-blog.zip .output

      # 上传
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: youus.zip
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      # 传到服务器
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "youus-blog.zip"
          target: "/web/youus/build"
          rm: true


      # 部署到服务器
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /web/youus/build && tar -xvf youus-blog.zip && cd .. && sh blog.sh
            


